server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuario?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
     ddl-auto: update
